### ISSUE TITLE
unable to get ssh to work.

### ISSUE THREAD

**Issue by Revel8804** [steevepay/gitlab-docker-letsencrypt#3]
I am unable to get the ssh pull and push to work. 

I am thinking the issue may have to be with the proxy not using port 22.
![image](https://user-images.githubusercontent.com/66074617/89903919-e2da3d80-dbad-11ea-9707-4e2de0d0a653.png)

**Comment by steevepay** [comment]
Hello @Revel8804,
You have to expose the port 22. Add the following lines inside the docker-compose service `gitlab-letsencrypt`:
```yml
ports:
    - '22:22'
```
Then restart the container and it should work.

**Comment by Revel8804** [comment]
Sorry you have a bit of a docker newbie here. 

Do i add it to this file?  
![image](https://user-images.githubusercontent.com/66074617/89906393-f4711480-dbb0-11ea-8bea-510153c7f9e6.png)

If not can you help point me to the correct file.

**Comment by steevepay** [comment]
You have to edit the docker compose on the `gitlab-docker-letsencrypt` project, the path:
`gitlab-docker-letsencrypt/docker-compose.yml`
Then on the  `gitlab-letsencrypt` service, add the following lines:
```yml
ports:
    - '22:22'
```
Restart the container with the command line: 
```shell
docker-compose up --build -d
```

**Comment by Revel8804** [comment]
Then on the gitlab-letsencrypt service, add the following lines:

Thats the part that i can not figure out where to go to add the lines.

**Comment by steevepay** [comment]
Here is the docker-compose.yml with the change:
```yml

version: "3.7"

services:
  gitlab-letsencrypt:
    image: 'gitlab/gitlab-ce:latest'
    container_name: ${CONTAINER_NAME}
    restart: always
    hostname: ${MAIN_DOMAIN}
    volumes:
      - '${GITLAB_DATA_PATH}config:/etc/gitlab'
      - '${GITLAB_DATA_PATH}logs:/var/log/gitlab'
      - '${GITLAB_DATA_PATH}data:/var/opt/gitlab'
    restart: unless-stopped
    env_file:
      - ./.env
    networks:
      - default
    ports:
      - '22:22'

networks:
  default:
    external:
      name: ${NETWORK}
```
Let me know if it is working
